exports.JOIN_CLUB_ROOM = 'JOIN_CLUB_ROOM';
exports.USER_JOIN_CLUB_ROOM = 'USER_JOIN_CLUB_ROOM';
exports.LEAVE_CLUB_ROOM = 'LEAVE_CLUB_ROOM';
exports.SEND_CLUB_MESSAGE = 'SEND_CLUB_MESSAGE';
exports.RECEIVE_CLUB_MESSAGE = 'RECEIVE_CLUB_MESSAGE';