exports.JOIN_CLUB_ROOM = 'JOIN_CLUB_ROOM';
exports.CLUB_ROOM_JOINED = 'CLUB_ROOM_JOINED';
exports.LEAVE_CLUB_ROOM = 'LEAVE_CLUB_ROOM';
exports.SEND_CLUB_MESSAGE = 'SEND_CLUB_MESSAGE';
exports.DELETE_CLUB_MESSAGE = 'DELETE_CLUB_MESSAGE';
exports.RECEIVE_CLUB_MESSAGE = 'RECEIVE_CLUB_MESSAGE';
exports.CLUB_MESSAGE_EDITED = 'CLUB_MESSAGE_EDITED';
exports.EDIT_CLUB_MESSAGE = 'EDIT_CLUB_MESSAGE';