exports.JOIN_ROOM = 'JOIN_ROOM';
exports.LEAVE_ROOM = 'LEAVE_ROOM';
exports.SEND_MESSAGE = 'SEND_MESSAGES_IN_CHATROOM';
exports.MESSAGE = 'MESSAGE';
exports.RECEIVE_MESSAGE = 'RECEIVE_MESSAGES_IN_CHATROOM';
exports.USER_JOINED_ROOM ="USER_JOINED_ROOM"